version: '2'
services:
  postgresql:
    image: postgres:10.4-alpine
    environment:
      POSTGRES_PASSWORD: admin18root
      POSTGRES_USER: admin
      POSTGRES_DB: gps_device
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
  app:
    image: openjdk:8-jdk-alpine
    depends_on:
      - postgresql
    entrypoint: 'java -jar /geodevice.jar'
    volumes:
      - ./build/libs/geodevice-0.0.1.jar:/geodevice.jar
    ports:
      - 8080:8080
    expose:
      - 8080