spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gps_device
    username: admin
    password: admin18root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQL92Dialect